[package]
name = "dtos"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
time = { version = "0.3.34", features = ["serde", "parsing"] }
uuid = { workspace = true, features = ["serde"] }
